// <auto-generated />
using EmployeeCars.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeCars.Migrations
{
    [DbContext(typeof(EMPLContext))]
    partial class EMPLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeCars.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Auto");

                    b.Property<string>("FirstName");

                    b.Property<string>("GosZnak");

                    b.Property<string>("LastName");

                    b.Property<string>("Phone");

                    b.Property<string>("Zvanie");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employes");
                });
#pragma warning restore 612, 618
        }
    }
}
